---
sidebar: sidebar 
permalink: technical-reports/data-security-index.html 
keywords: security features, storagegrid 
summary: 探索 StorageGRID 物件儲存解決方案的整合式安全功能。 
---
= 保護物件存放區中的 StorageGRID 資料和中繼資料安全
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
探索 StorageGRID 物件儲存解決方案的整合式安全功能。

這是NetApp® StorageGRID® 中眾多安全功能的概述，涵蓋資料存取、物件和元資料、管理存取和平台安全。它已更新，包含StorageGRID 12.0 發布的最新功能。

安全性是 NetApp StorageGRID 物件儲存解決方案不可或缺的一部分。安全性特別重要、因為許多適合物件儲存的豐富內容資料類型、本質上也很敏感、而且必須遵守法規與法規。隨著 StorageGRID 功能不斷進化、軟體提供許多安全功能、對於保護組織的安全狀態和協助組織遵循業界最佳實務實務非常寶貴。

本文概述了StorageGRID 12.0 中的眾多安全功能，分為五類：

* 資料存取安全功能
* 物件和中繼資料安全功能
* 系統管理安全功能
* 平台安全功能
* 雲端整合


本文旨在成為一份安全資料表——它沒有詳細說明如何配置系統以支援其中列舉的預設未配置的安全功能。這 https://docs.netapp.com/us-en/storagegrid/harden/index.html["StorageGRID 強化指南"^]可在官方 https://docs.netapp.com/us-en/storagegrid/["StorageGRID 文件"^]頁。

除了本報告中所述的功能外， StorageGRID 還遵循 https://www.netapp.com/us/legal/vulnerability-response.aspx["NetApp 產品安全性弱點回應與通知原則"^]。報告的弱點會根據產品安全性事件回應程序進行驗證及回應。

NetApp StorageGRID 為要求嚴苛的企業物件儲存使用案例提供進階安全功能。



== 何處可找到其他資訊

若要深入瞭解本文所述資訊、請檢閱下列文件和 / 或網站：

* NetApp StorageGRID ： SEC 17a-4(f) 、 FINRA 4511 （ c ）和 CFTC 1.31 （ c ） - （ d ）法規遵循評估 https://www.netapp.com/media/9041-ar-cohasset-netapp-storagegrid-sec-assessment.pdf[]
* StorageGRID文件頁面https://docs.netapp.com/us-en/storagegrid/[]
* NetApp 產品文件 https://www.netapp.com/support-and-training/documentation/[]




== 詞彙與縮寫

本節提供文件中所用術語的定義。

[cols="40,60"]
|===
| 術語或縮寫 | 定義 


| S3 | 簡易儲存服務： 


| 用戶端 | 可透過 S3 傳輸協定與 StorageGRID 進行資料存取的應用程式、或是用於管理的 HTTP 傳輸協定。 


| 租戶管理 | StorageGRID 租戶帳戶的管理員 


| 租戶使用者 | StorageGRID 租戶帳戶中的使用者 


| TLS | 傳輸層安全性 


| ILM | 資訊生命週期管理 


| LAN | 區域網路 


| 網格管理員 | StorageGRID 系統管理員 


| 網格 | StorageGRID 系統 


| 鏟斗 | 儲存在 S3 中的物件容器 


| LDAP | 輕量型目錄存取傳輸協定 


| 秒 | 證券交易委員會；規範交易所成員、經紀商或交易商 


| FINRA | 金融產業監管局；遵守 SEC 法規 17a-4(f) 的格式與媒體要求 


| CFTC | 商品期貨交易佣金；規範商品期貨交易 


| NIST | 國家標準和技術研究所 
|===