---
sidebar: sidebar 
permalink: technical-reports/commvault/sizing.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: 探索客戶與 NetApp IT 實作的 StorageGRID 組態使用案例。 
---
= StorageGRID 規模調整指南
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
請洽詢您的 NetApp 資料保護專家、以瞭解您環境的特定規模。NetApp 資料保護專家可使用 CommVault Total Backup Storage Calculator 工具來估計備份基礎架構需求。此工具需要 CommVault 合作夥伴入口網站存取權。如有需要、請註冊以取得存取權。



== CommVault 規模調整輸入

下列工作可用於執行探索、以調整資料保護解決方案的規模：

* 識別需要保護的系統或應用程式 / 資料庫工作負載、以及對應的前端容量（以 TB 為單位）。
* 識別需要保護的 VM/ 檔案工作負載和類似的前端容量（ TB ）。
* 找出短期和長期的保留要求。
* 識別所識別資料集 / 工作負載的每日變更率 % 。
* 找出未來 12 、 24 及 36 個月的預測資料成長。
* 根據業務需求定義資料保護 / 恢復的 RTO 和 RPO 。


如果有這項資訊可用、就可以完成備份基礎架構規模調整、進而分析所需的儲存容量。



== StorageGRID 規模調整指南

在您執行 NetApp StorageGRID 規模調整之前、請先考量工作負載的下列層面：

* 可用容量
* WORM 模式
* 平均物件大小
* 效能要求
* 已套用 ILM 原則


可用容量的數量必須符合您已分層至 StorageGRID 的備份工作負載大小、以及保留排程。

WORM 模式是否會啟用？在 CommVault 中啟用 WORM 時、這會在 StorageGRID 上設定物件鎖定。這將增加所需的物件儲存容量。所需容量會因保留期間和每個備份的物件變更數量而異。

平均物件大小是一種輸入參數、可協助調整 StorageGRID 環境中的效能大小。CommVault 工作負載使用的平均物件大小取決於備份類型。

下表依備份類型列出平均物件大小、並說明還原程序從物件存放區讀取的內容：

[cols="1a,1a,1a"]
|===
| 備份類型 | 平均物件大小 | 還原行為 


 a| 
在 StorageGRID 中製作輔助複本
 a| 
32 MB
 a| 
完全讀取 32 MB 物件



 a| 
將備份導向 StorageGRID （啟用重複資料刪除）
 a| 
8 MB
 a| 
1MB 隨機範圍讀取



 a| 
將備份導向 StorageGRID （停用重複資料刪除）
 a| 
32 MB
 a| 
完全讀取 32 MB 物件

|===
此外、瞭解完整備份和遞增備份的效能需求、有助於判斷 StorageGRID 儲存節點的規模。StorageGRID 資訊生命週期管理（ ILM ）原則資料保護方法可決定儲存 CommVault 備份所需的容量、並影響網格的大小調整。

StorageGRID ILM 複寫是 StorageGRID 用來儲存物件資料的兩種機制之一。當 StorageGRID 將物件指派給複寫資料的 ILM 規則時、系統會建立物件資料的精確複本、並將複本儲存在儲存節點上。

銷毀編碼是StorageGRID 由程式碼庫用來儲存物件資料的第二種方法。當 StorageGRID 將物件指派給已設定為建立銷毀編碼複本的 ILM 規則時、它會將物件資料分割成資料片段。然後、它會計算額外的同位元檢查片段、並將每個片段儲存在不同的儲存節點上。存取物件時、會使用儲存的片段重新組裝物件。如果資料片段或同位元檢查片段毀損或遺失、抹除編碼演算法可以使用剩餘資料和同位元檢查片段的子集重新建立該片段。

這兩種機制需要不同的儲存容量、如以下範例所示：

* 如果您儲存兩個複寫複本、您的儲存負荷會加倍。
* 如果您儲存的是 2+1 銷毀編碼複本、您的儲存負荷會增加 1.5 倍。


針對測試的解決方案、在單一站台上使用入門級 StorageGRID 部署：

* 管理節點： VMware 虛擬機器（ VM ）
* 負載平衡器： VMware VM
* 儲存節點： 4 個 SG5712 、含 4TB 磁碟機
* 主要管理節點和閘道節點：具有最低正式作業工作負載需求的 VMware VM


[NOTE]
====
StorageGRID 也支援協力廠商負載平衡器。

====
StorageGRID 通常部署在兩個或多個站台中、其資料保護原則可複寫資料、以防止節點和站台層級的故障。將資料備份到 StorageGRID 後、資料就會受到多個複本或銷毀編碼的保護、這些程式碼可透過演算法來獨立分離及重新組合資料。

您可以使用調整大小工具 https://fusion.netapp.com["Fusion"] 以調整網格大小。



== 擴充

您可以將儲存設備新增至儲存節點、將新的網格節點新增至現有站台、或新增資料中心站台、來擴充 NetApp StorageGRID 系統。您可以在不中斷目前系統運作的情況下執行擴充作業。
StorageGRID 可為儲存節點使用較高效能的節點、或是執行負載平衡器和管理節點的實體應用裝置、或只是新增其他節點、藉此擴充效能。

[NOTE]
====
如需擴充 StorageGRID 系統的詳細資訊，請參閱 https://docs.netapp.com/us-en/storagegrid-119/landing-expand/index.html["StorageGRID 11.9 擴充指南"]。

====